Microverse-Portfolio pull request
SolomonTheCoder/Microverse-Portfolio pull request #1
Opened 2023-01-18 11:22 UTC by SolomonTheCoder

This is my Microverse-Portfolio project.
In my project,
-Added an HTML file.
-Added a CSS file.

2023-01-18 13:03 UTC, didierganthier requested changes
Hi @SolomonTheCoder ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/cLwDB2j2a7JFdzQzYu/giphy.gif" />

## Highlights
- Linters passing ✔️ 
- Correct GitHub Flow ✔️ 
- Descriptive PR ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-01-18 13:03 UTC, didierganthier commented on style.css
> +}
Good job overall 💯  but play around with the margins and padding to make the dimensions match the Figma. You can easily see them by selecting any elements and looking at the right panel. 👀

2023-01-19 12:59 UTC, franclobo requested changes
Hi @SolomonTheCoder, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/213449094-cf2b0461-c79a-4a28-b35a-1c810f071667.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 12:59 UTC, franclobo commented on style.css
> +  background-image: url(header-shapes\ mobile.png);
- [ ] Instead, you used the correct background image it is repeating. Please 🙏🏽 fix it as requested by the last code reviewer to be similar to the Figma design.

| Figma design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/213445462-99dbc668-7b0b-4d6e-ad51-6b8168a52d29.png) | ![image](https://user-images.githubusercontent.com/58642949/213445561-d191849e-e392-4d8d-aef7-9695117a3150.png) |

2023-01-19 12:59 UTC, franclobo commented on style.css
> +  background-color: white;
- [ ] You don't need background color in the header, kindly play with the margin and padding to be similar to the Figma template.

2023-01-19 12:59 UTC, franclobo commented on style.css
> +}
- [ ] The title has three lines in the Figma template, please 🙏🏽 fix it to be similar to the original design. Kindly pay attention to the font styles and play with the margin and padding as requested by the previous code reviewer. 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/213447035-c59168f0-9fd8-4520-afe9-02dc62f5fba2.png)

2023-01-19 12:59 UTC, franclobo commented on style.css
> +}
- [ ] As requested by the previous code reviewer use flexbox to organize the icons, for a better user interface. 

- [ ] Kindly play with the margin and padding as requested by the previous code reviewer to be similar to the Figma design, please 🙏🏽 correct the size and the distance.

2023-01-19 12:59 UTC, franclobo commented on index.html
> +  <i class="fa fa-hand-peace-o" aria-hidden="true"></i>
- [ ] As requested by the previous code reviewer please add the `a `tag to the `li` items.

> Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href`

2023-01-20 10:36 UTC, levy002 approved these changes
## Hello @SolomonTheCoder 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 10:36 UTC, levy002 commented on style.css
> +}
- [OPTIONAL] I apologize for the previous reviewers who didn't mention this but the background image is not on the whole `body`. The background image needs to be placed to the `.header-main` container. If look carefully at the Figma design you will notice that the background is only on the introduction container. I highly recommend you to implement because if you don't it will cause of a lof of trouble in your styles in the coming project milestone.

2023-01-20 10:36 UTC, levy002 commented on style.css
> +}
- [OPTIONAL]  kindly make sure to align the contents of this container with CSS `flex-box`.

2023-01-20 11:11 UTC, merged