Feature
SolomonTheCoder/Microverse-Portfolio pull request #2
Opened 2023-03-23 10:53 UTC by SolomonTheCoder

In this branch, I
. Added a new section called "About Myself"
. Added new HTML and CSS files.

2023-03-23 13:59 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @SolomonTheCoder 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- Great job adding hover into your button but kindly follow the button styling: Active, Hover, and Pressed (see design). you must use the same color as is shown in the Figma design 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-23 13:59 UTC, MaganaAsiati commented on index.html
> +            </div>
- Kindly make sure that you use the `<p>` tag only for the paragraph. here you can use div or `<ul> `tag :+1: 
This way will be semantically correct and the screen readers and other technologies will thank you.

2023-03-23 13:59 UTC, MaganaAsiati commented on index.html
> +            </div>
- Kindly make sure that you use the `<p>` tag only for the paragraph. here you can use div or `<ul> `tag :+1: 
This way will be semantically correct and the screen readers and other technologies will thank you.

2023-03-23 13:59 UTC, MaganaAsiati commented on index.html
> +              <p class="P3">2015</p>
- Kindly make sure that you use the `<p>` tag only for the paragraph. here you can use div or `<ul> `tag :+1: 
This way will be semantically correct and the screen readers and other technologies will thank you.

2023-03-23 13:59 UTC, MaganaAsiati commented on index.html
> +              <p class="P3">2015</p>
- Kindly make sure that you use the `<p>` tag only for the paragraph. here you can use div or `<ul> `tag :+1: 
This way will be semantically correct and the screen readers and other technologies will thank you.

2023-03-23 13:59 UTC, MaganaAsiati commented on index.html
> +        </div>
- Kindly make sure that you use the `<p>` tag only for the paragraph. The technology in each category(e.g., "JavasScript", "HTML" and "CSS") is also a list `ul` and each of them a `li`or `<ul> `tag :+1: 
This way will be semantically correct and the screen readers and other technologies will thank you.

2023-03-23 13:59 UTC, MaganaAsiati commented on index.html
> +          <h2>Languages</h2>
- Kindly add the arrow button as shown in the Figma design. your design must stick to the Figma design as mutch as possible :+1: 

![image](https://user-images.githubusercontent.com/95297251/227222049-dae562bb-c948-4f63-a24d-a04c31fbb101.png)

2023-03-23 23:25 UTC, Kossi-stack requested changes
## Hi @SolomonTheCoder,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [OPTIONAL] Kindly edit the PR's title to something more descriptive. it can be "Portfolio: Finish Mobile Version PR".
 
 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-23 23:25 UTC, Kossi-stack commented on README.md
> +👤 **Author1**
- [OPTIONAL] Kindly replace Author1 with your name.

2023-03-23 23:25 UTC, Kossi-stack commented on index.html
> +        </div>
- [ ] As requested by the previous reviewer kindly fix the issue and let your code look like this
<img width="1086" alt="Screenshot 2023-03-23 at 16 05 41" src="https://user-images.githubusercontent.com/81444338/227384477-956f50b9-dab3-49f8-bcf3-d4a98aea1d57.png">

2023-03-23 23:25 UTC, Kossi-stack commented on index.html
> +          </ul>
-  [ ] Kindly follow the Figma Template (Ex: color, font size, etc...)

- Your Design
<img width="497" alt="Screenshot 2023-03-23 at 16 00 00" src="https://user-images.githubusercontent.com/81444338/227384987-c16d3b78-6300-487e-9c7c-7866eb820f7a.png">

- [ ] Figma  Design
<img width="1440" alt="Screenshot 2023-03-23 at 16 02 57" src="https://user-images.githubusercontent.com/81444338/227385047-67581978-ebd7-444c-89c5-c46ae3f23ce2.png">

2023-03-23 23:25 UTC, Kossi-stack commented on index.html
> +          </h2>
- [ ] Kindly fix the drop-down arrow

- [ ] Your design
<img width="501" alt="Screenshot 2023-03-23 at 16 18 28" src="https://user-images.githubusercontent.com/81444338/227385859-21c6c463-48e3-495d-acfa-eec4532ffae6.png">

- [ ] Figma Design
<img width="624" alt="Screenshot 2023-03-23 at 16 19 59" src="https://user-images.githubusercontent.com/81444338/227385906-df901bf3-f098-48b6-982a-547ad8167ed2.png">

2023-03-24 09:13 UTC, Shedrack-Sunday approved these changes
# STATUS: APPROVED ♻️♻️
Hi @SolomonTheCoder 

To highlight 👍🏽
- GitHub flow rightfully used ✅
- Professional README.md file ✅
-  No linter errors ✅

Your project is complete! There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-28 14:49 UTC, merged